### ISSUE TITLE
throttleMs behavior: Immediate first input creates edge case for minimum input validation

### ISSUE THREAD

**Issue by RomkaLTU** [47ng/nuqs#713]
## Context

What's your version of `nuqs`?

```
"nuqs": "^2.0.4",
```

What framework are you using?

- ✅ Next.js (app router)
- ❌ Next.js (pages router)
- ❌ React SPA (no router)
- ❌ Remix
- ❌ React Router
- ❌ Other (please specify)

Which version of your framework are you using?

```
NextJS 14.2.15
```

## Description

The throttleMs functionality is kind of strange. It will capture the first input instantaneously and then throttle according to the throttleMs parameter. That's pretty much it. This requires additional logic, for example, if you don't want to allow searching with just 1 letter.

**Comment by RomkaLTU** [comment]
In general, this throttleMs is not good for search text input. If you try to type, the second letter will be skipped. For example, if you try to type 'hello', it will appear as 'hllo'."

**Comment by franky47** [comment]
Yes, this is the expected behaviour for throttling: the URL is regularly updated, with an instant initial update.

While this works well for low-frequency UI elements like tabs or check boxes, high frequency ones (and particularly search) would benefit better from a debounce behaviour, where the update is **eventually** sent after a period of inactivity.

Debounce support is on the roadmap and should land soon, see #291.
